version: '3.11'

services:
  web:
    build: .
    container_name: 'test_stripe'
    command: bash -c "poetry run python3.11 src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:8000:8000"
